const dataFormTemplate = {
    informacion_personal: {
        nombres: '',
        apellidos: null,
        fecha_nacimiento: null,
        email: null,
        documento: null,
        direccion: null,
        barrio: null,
        ocupacion: null,
    },
    informacion_acudiente: {
        nombre_acudiente: null,
        apellido_acudiente: null,
        tel_acudiente: null,
        ocupacion: null,
    },
    historial_medico: {
        condiciones_previas: null,
        alergias: null,
        medicamentos_actuales: null,
    },
    informacion_tratamiento: {
        motivo_consulta: null,
        procedimiento_principal: null,
        notas_relevantes: null,
        eps: null,
    },
    anamnesis: {
        tratamiento_medico: null,
        ingestion_medicamentos: null,
        reacciones_alergicas: null,
        hemorragias: null,
        irradiaciones: null,
        sinusitis: null,
        enfermedades_respiratorias: null,
        cardiopatias: null,
        diabetes: null,
        fiebre_reumatica: null,
        hepatitis: null,
        hipertension_arterial: null,
        vih_sida: null,
        habito_higiene_oral: null,
    },
    examen_fisico: {
        artic_tempora_mandibular: null,
        labios: null,
        lengua: null,
        paladar: null,
        piso_de_boca: null,
        carrillos: null,
        glandulas_salivales: null,
        maxilares: null,
        senos_maxilares: null,
        musculos_masticadores: null,
        nervios: null,
        vascular: null,
        linfatico_regional: null,
        funciones_de_oclusion: null
    },
    odontograma: {
        supernumerarios: null,
        abrasion: null,
        manchas: null,
        patologia_pulpar: null,
        placa_blanda: null,
        placa_calcificada: null,
    },
    odontograma_denticion: { // Renamed from odontograma2
        '18': null,
        '38': null,
        '17': null,
        '37': null,
        '16': null,
        '36': null,
        '55 - 15': null,
        '75 - 35': null,
        '54 - 14': null,
        '74 - 34': null,
        '53 - 13': null,
        '73 - 33': null,
        '52 - 12': null,
        '72 - 32': null,
        '51 - 11': null,
        '71 - 31': null,
        '61 - 21': null,
        '81 - 41': null,
        '62 - 22': null,
        '82 - 42': null,
        '63 - 23': null,
        '83 - 43': null,
        '64 - 24': null,
        '84 - 44': null,
        '65 - 25': null,
        '85 - 45': null,
        '26': null,
        '46': null,
        '27': null,
        '47': null,
        '28': null,
        '48': null,
    },
    plan_tratamiento: { // Renamed from tratamiento
        remision: null,
        limpieza_profunda: null,
        clasificacion_angle: null,
        atm: null,
        lado_limpieza: null,
    },
    resumen: {
        notas_medico: null
    },
}

export default dataFormTemplate;
